### ISSUE TITLE
Not able to be used with node 10

### ISSUE THREAD

**Issue by yazshel** [LogansUA/typeorm-seed-extension#1]
Hi,

Thanks for your work on this project, it fills a big hole in TypeORM's functionality and I was pleasantly pleased to find it.

But I'm not able to install it in my Node 10 NestJS / TypeORM project because of the explicit `"engines": { "node": "^8.11.3"` }` in the `package.json`:

![image](https://user-images.githubusercontent.com/8703183/45520073-0dbd8a80-b7fb-11e8-9146-a04758f460bf.png)

Can this please be changed to `">= 8.11.3"` to enable usage on Node 10?

Cheers,

Timshel

**Comment by LogansUA** [comment]
@yazshel Hello, yeah sure, I'll change it today.

**Comment by LogansUA** [comment]
@yazshel Done in [4482a8d](https://github.com/LogansUA/typeorm-seed-extension/commit/4482a8dbbd1b253342d3172a81b56b4e31aba3cc)
