### ISSUE TITLE
Fails installing using npm

### ISSUE THREAD

**Issue by adamkrupke** [LogansUA/typeorm-seed-extension#2]
I get the following error when running `npm install typeorm-seed-extension -S`

> npm ERR! path /Users/Me/MyProject/node_modules/typeorm-seed-extension/lib/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/Me/MyProject/node_modules/typeorm-seed-extension/lib/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Me/.npm/_logs/2018-09-25T13_13_09_988Z-debug.log

**Comment by LogansUA** [comment]
@nomadoda Hello. I'll check it today.

**Comment by LogansUA** [comment]
@nomadoda please try [`v0.0.4`](https://github.com/LogansUA/typeorm-seed-extension/releases/tag/v0.0.4) version

**Comment by adamkrupke** [comment]
@LogansUA Yup, that seems to work

**Comment by LogansUA** [comment]
@nomadoda great :)
